### ISSUE TITLE
Set up a version-check 

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#100]
It would be awesome to put a check on the version somewhere, so I don't accidentally make a release that still has the prevoius version. 

An example of this error is the current [0.6.3-RC1](https://github.com/have-fun-was-taken/yafc-ce/releases/tag/0.6.3-RC1) pre-release. It states that it's 0.6.3-rc1, but the version in the program is still 0.6.2.

**Comment by veger** [comment]
What are you thinking about? A release script that has the version as an input?
It will
* update version -> commit
* tag version
* build packages
Then you'd need to push the commit and tag, and make a GH release and upload the packages.

On Linux/MacOS this is fairly easy to do I guess with a (bash) script. For Windows, I am not sure.

**Comment by have-fun-was-taken** [comment]
I don't know what exactly it will be. For instance, it can be a part of the build script that can write a message and terminate the build process if there's already a tag in the repo with the current Assembly/File version of the app.

**Comment by shihan42** [comment]
Perhaps we could use Github Actions for this?

https://github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps/

**Comment by have-fun-was-taken** [comment]
Thank you! I'll take a look at Github Actions if the build script will not cut it.

**Comment by shpaass** [comment]
Overall, rather than making a complicated automated solution, it's easier for me to just remember that I need to check the version in the app to be in sync with the release.
