### ISSUE TITLE
Add in-app explanations for fixed- and built-building counts

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#101]
It would be good to have an in-app explanation of what Fixed/Built Building Counts do. 
A question mark to the right from the buttons that shows explanation on hover would be good. If it's too hard to implement, an explanation on hovering over the buttons themselves would be the second best option, with an option to disable it in the settings.

**Comment by Dorus** [comment]
Do we know how this text should read? I'm not even sure i completely understand this function myself.

**Comment by veger** [comment]
Fixed building count: Forces a building (and it production) to the provided account
Built building count: Gives a warning/error when this number is surpassed (e.g. can be used to see when your base lacks buildings due to growth or something)
