### ISSUE TITLE
Error While loading mod Kux-OrbitalIonCannon (SE + K2)

### ISSUE THREAD

**Issue by UnReversed** [shpaass/yafc-ce#145]
- YAFC CE 7.0 & factorio 1.1.107

![image](https://github.com/have-fun-was-taken/yafc-ce/assets/171379891/6b19f5cc-4dc5-41b1-b4f6-a8bbe67c18c6)
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/171379891/6dbc38d7-2447-4084-8de1-47b3cb157579)

and fresh save file
[debug.zip](https://github.com/user-attachments/files/15751660/debug.zip)

PS maybe add ability to copy that error code?

**Comment by veger** [comment]
> PS maybe add ability to copy that error code?

Good idea
