### ISSUE TITLE
Provide means to copy&paste errors

### ISSUE THREAD

**Issue by veger** [shpaass/yafc-ce#146]
It would be convenient for error reporters to be able to copy&paste the errors from this screen, instead of making screenhsots:

![image](https://github.com/have-fun-was-taken/yafc-ce/assets/171379891/6b19f5cc-4dc5-41b1-b4f6-a8bbe67c18c6)

Requested in #145

**Comment by have-fun-was-taken** [comment]
For the exceptions, there is the `Copy to Clipboard` button. I gather it's not present for errors when loading mods?
