### ISSUE TITLE
Open project file instantaneously, skipping welcome menu.

### ISSUE THREAD

**Issue by Yukinyaa** [shpaass/yafc-ce#149]
Skip startup menu when project file (preferably `.yafc`) is specified in command line arguments.

# Additional Features
 - Add startup menu shortcut to recent project file automatically.

**Comment by DaleStan** [comment]
If you click on "Recent projects" on the Welcome screen, you should see a scrollable list of recent projects:
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/21223975/44587034-03db-4ad2-a4b8-b814d16dfbe0)

When opening a file from the command line, it appears to work if you supply all required arguments (data directory and optionally mod directory) and the project file path is (1) the full path to the file (2) the path to the file starting at "~/", or (3) the path _relative to the YAFC executable_.

That third option is surely not what was intended.

**Comment by Yukinyaa** [comment]
To achive what I was hoping for, command line requires major change. role of "--project-file" and <data-path> should be swapped. Not sure this is good, but will investigate further.****

**Comment by Yukinyaa** [comment]
Allow me to elaborate. Initially proposed 'feature' is this: User should be allowed to link `.yafc` filename extension to `YAFC.exe`, then just double clicking project file skips welcome screen then opens given project.

**Comment by Dorus** [comment]
Proposal: Add another command line argument like --skip-welcome-screen that works well together with both setting other arguments from command line/shortcut, as well as just loading your previous config.

Re: file association: that would also be nice. I wonder if that should be combined with skipping the welcome screen. If so, would windows allow us to register YaFC in a way to detect we're opened from a file?
I'm not familiar enough with that, but was reading up a bit on it here https://learn.microsoft.com/en-us/windows/win32/shell/fa-best-practices
