### ISSUE TITLE
Refactor PseudoScreen.Close()

### ISSUE THREAD

**Issue by DaleStan** [shpaass/yafc-ce#184]
`PseudoScreen.Close(bool save = true)` takes a parameter that is functionally never used, because `PseudoScreen.Save()` is an empty method that is never overridden.

The simple solution is to simply remove the save parameter and method, but the better solution is probably to override `Save` so it performs the appropriate operation. Several dialogs do not have an OK button (or equivalent) so those dialogs will need to have that button added in order for this to work.

**Comment by veger** [comment]
Implemented in #262
