### ISSUE TITLE
SchallAlienLoot has a richness error when loaded

### ISSUE THREAD

**Issue by green8751** [shpaass/yafc-ce#200]
im running YAFC 1.7.0, and Factorio 1.1.109
[bug report save schallloot YAFC.zip](https://github.com/user-attachments/files/16340777/bug.report.save.schallloot.YAFC.zip)

**Comment by green8751** [comment]
i double checked by makeing a new mods folder and installed the modslist off of the save i was planning to use them with.

**Comment by DaleStan** [comment]
As a workaround, you can change the loot richness setting to something other than "2×" or "4×".
