### ISSUE TITLE
Crash while loading mods

### ISSUE THREAD

**Issue by yangsuo1991** [shpaass/yafc-ce#201]
- Be sure that you are using the latest stable version of YAFC
- Try to remove outdated and disabled mods from your mod folder. Otherwise, you may still make a report, but you need to attach the whole contents of your mod folder, including all outdated and disabled mods.
- Specify the YAFC and Factorio version.
- While YAFC should work with mods down to Factorio 0.17 and maybe even earlier, we actively support only the latest stable versions.
- Attach a new game save file so it's possible to sync the mods with yours.

YAFC-CE 0.70, Factorio 1.1.109
Mods are Pyanodons, cybersyn and some others
Having the following error starting yesterday, YAFC was running perfectly before that, so I'm not sure waht the issues are:
<img width="470" alt="image" src="https://github.com/user-attachments/assets/9fe3cf84-3d8e-436b-8ffe-35dd5a9906fc">

**Comment by DaleStan** [comment]
Will you attach a save game file, please?

**Comment by yangsuo1991** [comment]
Problem solved, looks like it's related to recent instability issues with Intel 13/14th gen CPUs. Lowered core ratio a bit and the error is gone (along with so many other weird issues with Factorio and other games lol) and I could use it without problem. 
Thanks again!
