### ISSUE TITLE
[UX] Discern Yafc versions based on the deliverable

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#205]
A user beljihnwahfl on Discord brought the request to discern the Yafc version based on any file name in the deliverable.
One of the options is to copy a version from `AssemblyVersion` in `Yafc.csproj` ([link](https://github.com/shpaass/yafc-ce/blob/master/Yafc/Yafc.csproj#L7)) and put it in the name of deliverable archives during their creation.

Feel free to suggest other options on how to resolve the issue.

**Comment by Dorus** [comment]
We can probably modify the build script to include the version number in the resulting zip/tar.gz package.

Like this: https://github.com/Dorus/yafc-ce/blob/verson-in-release/build.bat

Doing this on windows command line is a small crime, probably easier on linux if you have grep, but i'm not familiar enough with that to get that working.

**Comment by veger** [comment]
I can build something similar for Linux build script, if grabbing the version from `Yafc.csproj` is the preferred way

**Comment by Dorus** [comment]
> I can build something similar for Linux build script, if grabbing the version from `Yafc.csproj` is the preferred way

It's the best i could find with a quick google.

**Comment by Dorus** [comment]
Mmm, i found one alternative, build first and then read the Yafc.exe file version?

```
powershell "(Get-Item -path .\Build\Windows\Yafc.exe).VersionInfo.FileVersion"
```

This trick let me run powershell from the command line, what makes my previous solution easier too. But i dont feel like updating it, the current solution of reading the .csfile should be sufficient too.

**Comment by shpaass** [comment]
Update: there is no `build.bat` anymore, so we can focus on making it work for Linux Shell.

**Comment by skofisk** [comment]
Reading the latest version from the git tag is also possible
`git tag --sort=committerdate | tail -1`

Would be nice if the release files could contains "Yafc-CE": `Yafc-CE-v0.7.4-Windows.zip`

**Comment by veger** [comment]
I do like adding `Yafc-CE` to the deliverables, what about you @shpaass? If you want I'll update #208 for an even better name.

**Comment by shpaass** [comment]
> what about you @shpaass?

I like the `Yafc-CE` in the name. The final result like `Yafc-CE-Windows-0.7.4.zip` would be good, I think.

> Reading the latest version from the git tag is also possible

Thank you for the idea! However, the version tag is currently created by the GitHub when I make a release. Creating it manually before the release would add another risk of making a mistake in the release process, and we'd like to prevent that.
