### ISSUE TITLE
[Discussion] Remove build.bat

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#206]
I use `build.sh` to make releases on Windows. For that, I use GitBash with the `zip` command installed on top of it, and I will continue to use it in the forseeable future. Therefore, I wanted to know if anyone uses `build.bat` at all.

This issue is related to https://github.com/shpaass/yafc-ce/issues/205 in a sense that if we delete `build.bat`, then we don't need to bother with implementing the version-fetch in cmd.

**Comment by veger** [comment]
I made the bash build script for when I made a non-official YAFC with some fixed a while back. I maintained the bat script to keep it in sync. (I guess @ShadowTheAge used it).

So for me we do not keep the script.

**Comment by DaleStan** [comment]
I also think it's fine to delete the batch script; having one release script is better than trying to maintain two, especially when they start getting complicated.

**Comment by shpaass** [comment]
done
https://github.com/shpaass/yafc-ce/commit/2e2ae23e69852d0a56a84404b7460f066d02b267

**Comment by Dorus** [comment]
I used it ❗ 

But if we don't want to maintain it that's ok, i can write my own script locally. All i used it for is to have a separate latest master from my own code modifications.

**Comment by shpaass** [comment]
The script is still there. You just need to checkout the commit before the one that deletes the script, and then you can keep it in your branch or git stash.

**Comment by shpaass** [comment]
To be more precise, you can revert the commit https://github.com/shpaass/yafc-ce/commit/2e2ae23e69852d0a56a84404b7460f066d02b267 in your branch. After that, you can rebase this branch as needed and check it out when you want to use it.

Apologies for the inconvenience.
