### ISSUE TITLE
[UX] Put the Legacy Summary button under the Summary button

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#225]
Despite being used by very few people, the Summary is located in one of the most-used places -- in the menu of the Plus button. That adds an extra click for the whole userbase for no reason. Let's fix that.

I propose to move the creation of a Legacy Summary sheet under the Summary button, on the same level in the "hamburger" menu on the upper-left.

The key metric is the following,
Current behavior:
1. A user wants to create a new sheet.
2. If they know about a shortcut, they use Ctrl+T. If they don't, they click a Plus sign _and have to click once more to choose between the creation of the sheet or the Legacy Summary_

Desired behavior:
1. A user wants to create a new sheet.
2. If they know about the shortcut, they use Ctrl+T. If they don't, they click on a Plus sign _that creates a new sheet_.

**Comment by DaleStan** [comment]
The plus sign dropdown also contains the "Import page from clipboard" option. Do you want to move that too?

**Comment by shpaass** [comment]
> The plus sign dropdown also contains the "Import page from clipboard" option. Do you want to move that too?

I bet that the Import functionality is used as infrequently as summaries, so I think that it would be good to move it somewhere to the bottom of the main menu too.
