### ISSUE TITLE
Yafc fails at energy producers that don't consume fuel

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#226]
Yafc version 0.8.0.

Steps to reproduce:
1. Open or create a Yafc project that includes Full-pY.
2. Make a new page, set 100MW of electricity as a desired product. That's an arbitrary number that is not too big or small.
3. Select an Electricity Generating recipe as a production recipe.
4. Select Fish turbine, HAWT, VAWT, Solar updraft tower, or any recipe that doesn't consume anything. 
5. Notice that Yafc fails to use the recipe and shows an error "model cannot be solved" at the top of the screen.

From what I remember of similar recipes, only the Solar Panel one works because it is hard-coded.

**Comment by shpaass** [comment]
Unless someone knows the reason for why it happens, the first step I'd suggest is to do some bisecting or release-checking to see if it was present before.

**Comment by veger** [comment]
IIRC this was always the case. I suppose it is related/similar to https://github.com/ShadowTheAge/yafc/issues/205 ?
