### ISSUE TITLE
Problems with detecting DirectX version

### ISSUE THREAD

**Issue by Arengror** [shpaass/yafc-ce#233]
Long story short, I using YAFK 0.8.1 but it crash during calculator window loading.

With my racoon hands and message from shpaass (Do you have DirectX12 on your machine? We've changed the default version to 12, so it might be the reason. It should've swapped to 9 otherwise though.) i searched trough log and found out few things

1)Apparently I have 6 render drivers
2)One of them is DX12

The problem is- I using Windows 10 and GTS450. 

GTS450 too old for DX12 and ,according to Intel, DX12 is PREINSTALLED on Windows 10 and 11, so I can't delete DX12 files to manually resolve that issue. That's why during calculator loading phase YAFC tries to use DX12 but instead he just die.

And to save some time, driver finder is here - PickRenderDriver , line 91 at yafc-ce/Yafc.UI/Core/WindowMain.cs

Don't even know if I can add anything except it was fun to dig trough.

YAFC log attached
[yafc20240811.log](https://github.com/user-attachments/files/16570886/yafc20240811.log)

//How does SDL_GetRenderDriverInfo work?
//Will "SDL.SDL_GetRenderDriverInfo(1, out SDL.SDL_RendererInfo rendererInfo)" show acting driver?

And for now I gonna use older versions.

**Comment by sfoster1** [comment]
Oh, that’s a really interesting problem. 

For your specific questions:
- [SDL_GetRenderDriverInfo(…)](https://wiki.libsdl.org/SDL2/SDL_GetRendererInfo) does get information about a specific render driver. The information is in the rendererInfo object passed as an out parameter. We log the name of the driver, but there’s other information in [the object](

**Comment by veger** [comment]
> Another option might be a setting, which we could actually save in the project file and initially set in the loading panel, to fall back to a software renderer.

There is also a global settings, e.g. to store the recent projects. This would be the ideal place to store a 'software render' configuration, as this setting would not be project dependent but installation dependent.
