### ISSUE TITLE
[Todo] Remove bit-shifts from some Enums

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#266]
For instance, `ProductionLink#Flags` is not referenced in the solver. 
I think there is no need to squeeze out that performance by sacrificing the ease of understanding the code.
I think it is a good idea to refactor this Enum into one without bit shifts.

> This issue was made to track the cases of this problem throughout the codebase. I refernce this issue in the code as 
`// TODO(shpaass/yafc-ce/issues/266): remove bit shifts from this Enum.`

What do you guys think?

**Comment by DaleStan** [comment]
I think that's a reasonable use of a `[Flags]`-style enum. What would use instead of the shifts (or instead of the the whole enum)?

**Comment by shpaass** [comment]
I should've thought a bit more before making this issue. My initial idea was to convert it to an object with bools. Something like
```
public class ProductionFlags {
    public bool LinkNotMatched {get; set} = false;
    and so on
}
```
but now that I thought about it, I'm not at all sure if it makes things better. Bitwise operations don't look that bad in comparison.

Overall, I need to read up on that. Thank you for the check!

**Comment by shpaass** [comment]
As written in the MSDN [article](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/enum#designing-flag-enums):
> DO use powers of two for the flag enum values so they can be freely combined using the bitwise OR operation.

In other words, everything is fine with bitwise operations and the enums that use powers of two.
