### ISSUE TITLE
[pY] Incorrect numbers for Oil burner

### ISSUE THREAD

**Issue by qazzz789** [shpaass/yafc-ce#272]
* Occurs with YAFC-CE 0.9.0 
* Windows 10 x64
* Reproduced in a new 0.9.0 project

Upgraded yafc and the value for the oil burner is incorrect.

| YAFC-CE 0.8.0   | YAFC-CE 0.9.0  | YAFC-CE 0.9.0 allow overproduction steam |
| ------------- | ------------- | ------------- |
| ![creosote_0 8 0](https://github.com/user-attachments/assets/2459401e-deb7-49dd-84c5-9f165511dab5)  | ![creosote_0 9 0](https://github.com/user-attachments/assets/a01c1f31-702c-4b0a-a214-336b6ad8fd0e)  | ![creosote_0 9 0_over_steam](https://github.com/user-attachments/assets/fd2b65e7-4293-4274-b748-b7d8e84fcb76)|

the in game rate for the oil burner burning light oil is 3.6k/min verified by rate calculator and timing how much a tank fills up in a minute
![image](https://github.com/user-attachments/assets/f8f33aad-d6d4-4c2d-8a8f-7b07e2262e80)

yafc project: [project_new.zip](https://github.com/user-attachments/files/16919133/project_new.zip)
factorio sample save: [py_test.zip](https://github.com/user-attachments/files/16919296/py_test.zip)

**Comment by shpaass** [comment]
For reference: might be related to https://github.com/shpaass/yafc-ce/issues/232

**Comment by shpaass** [comment]
Fixed by https://github.com/shpaass/yafc-ce/pull/273
