### ISSUE TITLE
[pY] Prefer updated Steam recipes

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#276]
Steps to reproduce:
1. Create a new pY-AE project and create a sheet with Steam 250 as the desired product. Alternatively, do that in an existing pY-AE project.
2. Click on the desired product to choose the recipe for it. Click to see the full list.
3. Notice that the new recipes -- the ones that use modules -- are disabled.

~~The desired behavior on pY-AL 1.2.27+ is that the old recipes are disabled-by-default, and the module-recipes are enabled instead.~~

**Comment by SWeini** [comment]
desired behavior after a quick chat with notnotmelon:
if assembling machine has fixed_recipe, that recipe should be handled as available when used in that assembling machine

https://discord.com/channels/560199483065892894/1210135763422027837/1271859023213494292

this should make the new recipes available

not sure about making the old recipes disabled - after all the boilers still exist in existing savegames, and you can even build more of the old boilers via copy&paste or blueprints - I believe the old boilers should be left available

**Comment by shpaass** [comment]
Thank you for the info!

**Comment by DaleStan** [comment]
Yes, the new recipe should be accessible. I thought I'd fixed that at some point in the past, but I can't find that change now.

The old boiler and recipe (technically a mechanic) are also accessible, since the boiler still exists and can be placed by bots.

**Comment by Dorus** [comment]
Yeah i described the same problem here https://github.com/shpaass/yafc-ce/issues/232#issuecomment-2336463478
