### ISSUE TITLE
Move mining and research bonuses from Module Autofill Parameters

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#296]
Users expressed an opinion that the Mining and Research Bonuses are located in a non-intuitive place. They are currently located in the Module Autofill Parameters.

![grafik](https://github.com/user-attachments/assets/27214da7-b947-4bca-a2f9-da3e439ead85)

We settled on moving them to the Milestones window. The reason for that is that unlike most of the settings in Preferences, these bonuses change throughout the gameplay. 
Moving Mining and Research Bonuses to the Milestones-window would incentivise a player to update them when they move up a tech tier.

Edit: Turns out that the opinions differ. Let's continue the discussion to reach a consensus.

**Comment by veger** [comment]
We do not have a project settings page? (Only a global/user settings). As this would be very related to project settings.

If not, then the milestone view seems to be a nice place to add these (tech related) settings yes. (The whole milestone view could have some revamp, as it is not compact/clean ATM)

**Comment by shpaass** [comment]
Ah, it seems that the opinions differ. Then let's the discussion. Some of the players are on Discord, so I suggest to reach a consensus on Discord and then post the summary there. I falsely assumed that everyone was in agreement.

**Comment by shpaass** [comment]
> [...] the argument I see for moving these bonuses to the milestones window also applies to at least the inserter capacity setting, and likely also the default belt/inserter settings and the target technology. These seem like additional things that can or do change as you progress through the tech tree.

Taking that into account, if we were to move all of these things into Milestones, that would put too much pressure on the Milestones page -- some players may select many custom milestones, and the page should be able to give them enough space. However, with its space being taken away by the settings, the Milestones page may have trouble with that. 

How about having two pages of Preferences? The first page would be the project-settings, and the second page would be the rest.
The first page would contain things that change with the progression, like:

- Mining and research bonuses
- Inserter capacity
- Default belts and inserters
- Target technology

If we want to remind a player about these settings on the Milestone page, then we can make a hint-like passage and/or a button at the bottom of the Milestone page, like "Moving up a tier? Don't forget to update your progression-related settings in Preferences."

Another reason why I come back to the idea of putting mining and research bonuses into Preferences is because if we put some settings into Milestones, then the settings would be scattered across two unrelated screens (Milestones and Preferences), which I want to prevent. Therefore, my idea is to consolidate project-settings as the first page in Preferences.

**Comment by veger** [comment]
:+1: 
As mentioned earlier, I think a per project settings page (next to a 'general' settings page) would be ideal for this. With your idea of adding a hint/button to point to this project settings page in the milestone page it should funnel the users from the 'active' place (they just updated their milestones) to the project settings page.
