### ISSUE TITLE
Focus input field when clicking "set building count" or "set production count"

### ISSUE THREAD

**Issue by gisanka** [shpaass/yafc-ce#297]
Current steps:
1. Click on Set building count or Set production count
2. _Click on the field to enter the number_
3. Enter the number

Desired steps:
1. Click on Set building count or Set production count
2. _The field is already focused, so no need to click._
3. Enter the number

The initial wording of the request: 
>would be great if the number field would gain focus after clicking on items which triggers building or production counts, now I have to do a extra click on the field every time before entering the number

**Comment by Fabelair** [comment]
hey @shpaass, can I work on that for u?
