### ISSUE TITLE
Migrate from float to double

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#298]
The ticket https://github.com/shpaass/yafc-ce/issues/284 uncovered the following information:
* There is no architectural reason for Yafc to use `float`.
* `float` is [risky](https://stackoverflow.com/questions/407970/when-to-use-a-float/407991#407991) to use.

Therefore, it would be good to migrate from using `float` to `double` in our codebase, where possible.

**Comment by shpaass** [comment]
I recently thought more about this ticket. I have my doubts. We discuss it on discord. I'll post the summary here once we have a consensus.

**Comment by shpaass** [comment]
After discussion with the person who started to work on it, @skullbearer, we decided to abort the ticket for the following reason:
> The chance of breaking things is much bigger than the benefit that we get from the conversion. In other words, the "precision" or other vague benefits of migrating to `double` are not worth the risk of introducing new bugs by changing that much of the actual code

**Comment by skullbearer** [comment]
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/numeric-conversions

Implicit conversion from double to float is not allowed in C#, so at testing the compiler will (should) throw an error.

**Comment by shpaass** [comment]
So essentially, I'd suggest to use doubles in the new code and change the old code to doubles if necessary.

Regarding the implicit conversion being forbidden, we can do the explicit conversion if required.
