### ISSUE TITLE
YAFC won't create project if you don't own the DLC

### ISSUE THREAD

**Issue by lehitom** [shpaass/yafc-ce#323]
YAFC CE v2.0.0
Factorio v2.0.8

When it attempts to create a project, it detects the expansion as active (I don't own it) and the mod list only contains the base game. After hitting disable and reload 4 times, it hits a critical error. This is a fresh install of the game as of 2.0.7, I moved my 1.1 files elsewhere.

![image](https://github.com/user-attachments/assets/0e5844d0-29ff-4224-82b5-2c05e8ec9dbc)

**Comment by veger** [comment]
Yes... I saw that the space age mod is hard-coded enabled:

https://github.com/shpaass/yafc-ce/pull/320/commits/dca64d4bd033e900718303ba5bfd5e69d6666523

I do not like this change myself, but the PR #320 got merged very quickly.

@shpaass Why don't we read the mod list and check if it is enabled or not? Same goes for hard-coded Quality, if people disable this (for reasons) they cannot use YAFC! (Maybe we need a separate ticket to discuss this, or we use this one?)

**Comment by shpaass** [comment]
The PR https://github.com/shpaass/yafc-ce/pull/320 got merged very quickly to have at least some support of Factorio 2.0.
I'm not against reading the mod list or making the quality optional.
We can discuss your concerns here, or if they don't fit the ticket, you can create a separate one.

**Comment by veger** [comment]
My proposal would be:
1. read mod list and check for the DLC mods
2. when they are found we can set some 'static' variable, so the rest of YAFC can easily add support for them
3. we fix all hard-coded space-age and quality support by enabling them only when the corresponding mds are detected/loaded.
4. (bonus) we could do the same (in the future) for py related stuff like TURD support?

If we all agree with this proposal, I guess we need to figure out some flexible way (plugins?) to add mod specific support/code for space-age, quality (and py).

**Comment by veger** [comment]
@lehitom For now, I would suggest to revert to the previous YAFC version, until we fixed this (it might take a little). I think the newest version only/mostly added v2.0 support, so there is not (much) you would miss out on.

**Comment by veger** [comment]
Oh... there were some breaking changes for the base game as well? :disappointed: 
Then we need to quickly fix this ticket, so players without the DLC can use it again

**Comment by shpaass** [comment]
I'll be free in around 10 hours, but it will take time learning this part of Yafc.

**Comment by veger** [comment]
While waiting for the agreement or on counter proposals, I'll work on decoupling space-age/quality/elevated-rail from the base game. I guess we need to this at the least...

**Comment by lehitom** [comment]
> Oh... there were some breaking changes for the base game as well? 😞 Then we need to quickly fix this ticket, so players without the DLC can use it again

Yup, just spun up my YAFC CE v0.9.1 with factorio 2.0.9 (Base only, don't own DLC) and I get a wall of red, not even a complete error.

![image](https://github.com/user-attachments/assets/219bf9c5-3877-447e-9b47-f99180e8f7a3)

**Comment by shpaass** [comment]
> Yup, just spun up my YAFC CE v0.9.1 with factorio 2.0.9 (Base only, don't own DLC) and I get a wall of red, not even a complete error.

Yafc v0.9.1 is not meant to work with Factorio 2.x. Too much stuff changed in the game.

**Comment by veger** [comment]
There was nothing (code-wise) that requires the Space Age DLC/mods to be loaded. So removing loading these hard-coded enabled mods seemed to be enough.

So it does not seem to be necessary (for now) to think about keeping track of certain feature to be available or not. In a later stage when we want to support 'quality', 'spoiling', 'TURD', etc., we do need to think about it.

**Comment by veger** [comment]
This should have been fixed in the v2.1.0 release, could you verify so we can close the issue?

**Comment by lehitom** [comment]
v2.1.0 release works just as good as the custom build I did of the original patch on shpass's branch. So all good here

Thanks again!
