### ISSUE TITLE
Be able to change dark-/light-mode in Preferences

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#328]
Many players can't find the dark-/light-mode button because it's not present in Preferences. It is only present as a lightbulb on the welcome screen. 

I think there is no specific reason why it should be only on the welcome screen. Users expect it in Preferences, so let's add it to Preferences.

**Comment by veger** [comment]
Might be that we cannot switch the themes after the main screen is loaded... :thinking:
If so, this might be the reason why ShadowTheAge choose to add the lightbulb on the welcome screen.

**Comment by DaleStan** [comment]
No real reason we can't swap to or from dark mode in the Preferences screen, except that you get a mixed view until you click "Done":
![image](https://github.com/user-attachments/assets/ba1379a3-3171-4c54-85f7-040fb6affa90)
