### ISSUE TITLE
[UI design] Recipe productivity technologies

### ISSUE THREAD

**Issue by DaleStan** [shpaass/yafc-ce#331]
2.0 introduces a `change-recipe-productivity` technology effect. How much support do we want to provide for this?
1. The minimum level of support would be to create a "Recipe productivity bonuses" section in the preferences, where users can select recipes and then set the bonus for each recipe. If the user sets a different bonus for low-density-structure than casting-low-density-structure, or sets any bonus for iron-plate, that's on them.
2. The next level up would still create a "Recipe productivity bonuses" section in the preferences, but preload it with only the recipes that are mentioned in a `change-recipe-productivity` technology effect. They're still responsible for keeping linked values in sync.
3. The highest level would instead create a "Technology levels researched" section, where the user could specify they've what level they've completed for each technology with a `change-recipe-productivity` effect, and it would be on us to convert that into a productivity bonus.

1 is the simplest for us. 2 is most like the current behavior for research speed and mining productivity, but still requires parsing the new technology effect. 3 is easiest for the user, but opens us up to feature requests for setting the research level for mining prod and research speed, or whether steel-axe has been researched, and maybe even damage levels to calculate ammo usage when reducing asteroids to chunks [^1]. It also risks "I checked steel-axe in the milestones, but it didn't update in the preferences" bug reports.

Translating from the current raw-percentage settings to technology levels may not be possible, if the user has entered a value that doesn't actually happen in-game, and adding more such values can only make this worse.

[^1]: I've argued against entering explicit tech levels in the past, but my argument doesn't hold up as well now that there are 20 productivity settings, with possibly more in mods, instead of 2. (Plus another for research speed.)

**Comment by SWeini** [comment]
4. The super highest level would be a mod that can export the current state of technology levels to be imported by YAFC. This can also be used to have fine control over availability of recipes. This could also transfer the state of recipes that were locked/unlocked via script in mods.

2. should be easy enough to implement, therefore my vote goes to preloading all the recipes that may have effects.
