### ISSUE TITLE
Kux-BlueprintExtensions, mod.lua

### ISSUE THREAD

**Issue by AquiloSpiritus** [shpaass/yafc-ce#335]
The mod has no recipes...

(Kux-BlueprintExtensions, mod.lua):6: attempt to concatenate field 'version' (a nil value)
stack traceback:
[C]: in function '__concat'
(Kux-BlueprintExtensions, mod.lua):6: in main chunk
[C]: in function 'require'
(Kux-BlueprintExtensions, data.lua):1: in main chunk

**Comment by shpaass** [comment]
Do I understand it correctly that the mod Kux-BlueprintExtensions does not affect calculations?
If so, then I suggest to disable it for Yafc. For that, please copy the mod folder, disable the mod in the copied `mod-list.json`, and point Yafc to the copied folder.

Please let me know if that solves your issue.

**Comment by AquiloSpiritus** [comment]
This solves the problem (already did this), but I would like automation. I am reporting the problem in case it happens again in other mods.

**Comment by shpaass** [comment]
There is a discussion about it: https://github.com/shpaass/yafc-ce/issues/286. Feel free to contribute to it.

**Comment by AquiloSpiritus** [comment]
"Disable & reload" disables only the problematic mod? Then that solves the problem (I thought it disabled the ENTIRE mod folder)

**Comment by shpaass** [comment]
Yes, I think "Disable & reload" disables only the problematic mod.

**Comment by shpaass** [comment]
Checked. If you hover over the button, it tells you exactly that. I'll close this issue for now. Feel free to reopen it if necessary.
