### ISSUE TITLE
Show total output for scrap

### ISSUE THREAD

**Issue by CricketBr** [shpaass/yafc-ce#337]
Problem description: Scrap yields a lot of different items. I want to know the total throughput required to get them all out. For instance, if Scrap were to produce 10x/s and 20y/s, then I'd want the number somewhere that scrap outputs a total of 30 items per second.

![image](https://github.com/user-attachments/assets/33293312-d81f-433b-b527-3d2b204910c3)
This is an example of current scrap output for 1 spm.

Similarly, in SeaBlock, I want to saturate a belt with geodes, from the recipe that produces many colours at once.

**Comment by shpaass** [comment]
I've reworded the request to be easier understood. Please verify that it still reflects what you want.

**Comment by CricketBr** [comment]
Yes, it still reflects what I want. Thank you.
