### ISSUE TITLE
Option to warn on building count change

### ISSUE THREAD

**Issue by Funtime60** [shpaass/yafc-ce#349]
I use YAFC to plan my Py+Al factories and due to the complex nature of this modpack I often find some dependant recipes have changed building count. It'd be nice if YAFC could warn me that a change requires a different number of buildings for dependents/suppliers.

**Comment by DaleStan** [comment]
I think you should be able to do this with the "Built building count" feature. Click "Set built building count" in the crafter dropdown:
![image](https://github.com/user-attachments/assets/8013e84c-d440-4a9f-a56d-c8e29583589b)
If you've overbuilt, set the number of buildings you have in the new edit box. If you have enough, it looks like this:
![image](https://github.com/user-attachments/assets/1180d7c4-ddf0-413f-b7ce-03022b812081)
and if you don't, it looks like this (hover the (!) icon to see the warning):
![image](https://github.com/user-attachments/assets/8134934d-b36f-456a-93f6-ebd4c986c559)

This lets you overbuild early, if you want, and Yafc will only warn you when you exceed the amount that you built.

**Comment by DaleStan** [comment]
Let us know if this doesn't do what you need
