### ISSUE TITLE
make Self-contained bundle

### ISSUE THREAD

**Issue by mrSumkin** [shpaass/yafc-ce#359]
Please make a self-contained build of the application, for those who cannot install .Net 8 for technical or other reasons.
This is possible, and is described briefly here https://learn.microsoft.com/en-us/dotnet/core/deploying/.
I have used similar applications before and it works.

Thanks.

**Comment by shpaass** [comment]
Tested it now. The release with the `--self-contained` option for Windows is ~50MB. The rest are already self-contained.
I think it is possible to release a self-contained version in addition to the one that we publish now.
Other developers, what do you think?

**Comment by veger** [comment]
We can just add this as a separate step in the `build.sh` if you are fine with this? (It is a bit of extra for when you make a release, as there is one more file to take care of)
