### ISSUE TITLE
Investigate the question mark when hovering over a recipe

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#43]
When choosing a production recipe, when hovering over some recipes, the first line sometimes is `?` instead of `A recipe to create something`: 
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/73699379/d628926e-d30e-4139-8bcc-c2b67416bf5a)
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/73699379/9738d79c-fd86-4d27-aed2-a6960b188f28)

It would be useful to understand why exactly the question mark is shown because it is shown quite often, and it can bring confusion to the end user.

A mod-list to replicate the exact same situation would be quite large, but the bulk of the mods is Pyanodons Alternative Energy and all its mandatory dependencies.

**Comment by Dorus** [comment]
The ? stems from FactorioDataDeserializer line 568.

It arrives on line 565 with a luaTable containing a localised_descripption of 3 elements, an ?, and 2 other luaTable

![afbeelding](https://github.com/have-fun-was-taken/yafc-ce/assets/4461459/4c7d60e7-c0fb-4268-8f83-f9311b85751c)


Moving into the `Localize(table)` function, it decides to call `Localize("?", table)` that in turns calls `FactorioLocalization.Localize("?")` that returns `null`. Then on line 491 it calls table.ArrayElements<string>(table), which returns just the "?". So basically it's just parsing what's in the data. I'm not sure how it should have parsed this different.

If i had to guess where this dataset comes from:
![afbeelding](https://github.com/have-fun-was-taken/yafc-ce/assets/4461459/ad18b5bf-1dbb-4edd-83ef-2f01b7631c81)


It seems pycoalprocessing_2.1.22\prototypes\functions\functions.lua:1302 adds a entity-description like this:

```lua
-- adds some text to a prototype's localised description
function overrides.add_to_description(type, prototype, localised_string)
	if prototype.localised_description and prototype.localised_description ~= '' then
		prototype.localised_description = {'', prototype.localised_description, '\n', localised_string}
	else
		if type == 'item' and prototype.place_result then
			for _, machine in pairs(data.raw) do
				machine = machine[prototype.place_result]
				if machine and machine.localised_description then
					prototype.localised_description = {
						'?',
						{'', machine.localised_description, '\n', localised_string},
						localised_string
					}
					return
				end
			end

			prototype.localised_description = {
				'?',
				{'', {'entity-description.' .. prototype.place_result}, '\n', localised_string},
				{'', {type .. '-description.' .. prototype.name}, '\n', localised_string},
				localised_string
			}
		else
			prototype.localised_description = {'?', {'', {type .. '-description.' .. prototype.name}, '\n', localised_string}, localised_string}
		end
	end
end
```

After going trough all this code, i'm still clueless what's going on here lol.

**Comment by SWeini** [comment]
that's a new feature introduced in 1.1.73, officially called "fallback group"

for more information see https://forums.factorio.com/viewtopic.php?f=3&t=104293 and https://forums.factorio.com/71553

**Comment by have-fun-was-taken** [comment]
Thank you for the info!
Practically, do we want to hide this question mark, or do you have other ideas about how to handle it?

**Comment by craig-johnston** [comment]
I was playing around to see if I could fix this. This snippet helps some cases e.g. Bonemeal (the item) is ? in main but with the following fix displays the right info. But it then causes items where there is no localisation (e.g. the diesel recipe) to show the localisation key: "recipe-description.diesel"

```
        private void Localize(object obj)
        {
            if (obj is LuaTable table)
            {
                if (!table.Get(1, out string key))
                    return;

                if (key == "?")
                    Localize(table[2]);
                else 
                    Localize(key, table);
            }
            else localeBuilder.Append(obj);
        }
```

What's the actual desired behaviour if a localisation is missing?
* Show ?
* Show the key (e.g. "recipe-description.diesel")
* Show nothing

**Comment by craig-johnston** [comment]
If we follow what Factorio seems to do, it'd simply fail the first localisation lookup and return empty string for that specific item.
In this specific case ("recipe-description.diesel") that would mean there's no description for the recipe and the next part of the localisation occurs (the "affected by productivity" string is put in the description).
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/13162232/632b7f0d-0b03-4f39-8133-2f36b327dc8b)

**Comment by craig-johnston** [comment]
https://github.com/have-fun-was-taken/yafc-ce/pull/63 might be useful as a starting point for fixing this properly.

**Comment by have-fun-was-taken** [comment]
> What's the actual desired behaviour if a localisation is missing?

I think it's either to show nothing or the key. There are arguments for both of the approaches, so it's up to you.

**Comment by Dorus** [comment]
Wouldn't you default to english then? If that's also missing i guess the above.

**Comment by have-fun-was-taken** [comment]
> Wouldn't you default to english then?

From what I see, YAFC already uses English everywhere, no matter what language your system or the game is using.

**Comment by Dorus** [comment]
![afbeelding](https://github.com/have-fun-was-taken/yafc-ce/assets/4461459/c87b4d78-7b27-4aaa-9dbc-2f116fbf3131)
Not for me, it has the same parts dutch as Factorio has ingame.

**Comment by craig-johnston** [comment]
Here are the before and after for what's currently implemented in https://github.com/have-fun-was-taken/yafc-ce/pull/63
It tries to match what's what Factorio does as closely as possible.

Before:
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/13162232/8b26888c-af43-49da-a4f4-7f1c0c13b378)
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/13162232/dd5c9a58-2615-4173-b870-9bc6014d167c)
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/13162232/6e37650b-9470-4408-9bc0-27c314d64b69)

After:
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/13162232/58f620b9-6bf7-4b7b-aefc-ab6df6e237eb)
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/13162232/8f964fbb-49a0-4f18-87de-bf28e503e683)
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/13162232/2b53630c-9878-48e6-b856-f8439b9f0e1e)
