### ISSUE TITLE
Make the search field focused automatically

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#44]
Current behavior:
1. Make a new production sheet.
2. Click the plus sign to add Desired Products.
3. Click the search field or press `Ctrl` to focus the search field.
4. Enter the search query and choose the product.

Desired behavior:
1. Make a new production sheet.
2. Click the plus sign to add Desired Products.
3. The search field is focused automatically. You don't need to click or press anything.
4. Enter the search query and choose the product.

**Comment by shihan42** [comment]
The input box isn't focused automatically, that's right. But if you just start typing away (instead of pressing crtl), the keyboard input goes straight to the search field.

It could be explicitly focused for more visual clarity, though.

**Comment by shihan42** [comment]
So, this is surprisingly hard to solve. I don't have a working solution that automatically sets the focus to the input field. Entering keys works, but the visual indication is not there.
Perhaps someone wants to give this a try?

**Comment by shpaass** [comment]
Done by https://github.com/shpaass/yafc-ce/pull/221
