### ISSUE TITLE
The Plus sign in the dark mode tires the eyes

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#97]
In dark mode, when adding a desired product, doesnt' the Plus sign seem blurred to you? Or is it just me?

**Comment by veger** [comment]
You mean this one? 
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/171827/3c041ef1-51fc-4227-a5ca-fc8bffd490a9)

It definitely is blurry: zoom in on the bitmap and you can see some (weird) aliasing going on.

**Comment by have-fun-was-taken** [comment]
Yes, this one.

**Comment by veger** [comment]
Thanks... now I cannot unsee it and my eyes are getting tired too :trollface: 

Let's make a new version of this icon and reduce the blurriness :+1:
