### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#98]
version: Windows, latest current master (81ed668), Pyanodons AE.

![grafik](https://github.com/have-fun-was-taken/yafc-ce/assets/73699379/8cb99e11-64a9-4395-897e-bb6184ea3f0c)

The wrong coloring of the desired product is handled in https://github.com/have-fun-was-taken/yafc-ce/pull/94.

The wrong result is that the Arqad Nest is listed in Extra Products as 1/s when 1/s of them is being produced overall, and there is a 1/s demand of them from Desired Products.

~~Perhaps this bug happened because something went deep into the `float` precision because of the number of buildings and how slow they are without modules.~~ However, it needs to be noted that it happened without going too low on the ingredients like it was in https://github.com/have-fun-was-taken/yafc-ce/issues/80.

**Comment by Dorus** [comment]
These buildings should be disabled without the proper modules anyway, does setting modules fix it? (Testing that could shed some light on the tiny float error speculation)

**Comment by have-fun-was-taken** [comment]
Nice catch! Turns out that inserting modules doesn't fix it. 

![grafik](https://github.com/have-fun-was-taken/yafc-ce/assets/73699379/03ea7e29-8273-4116-b155-836a6ea5c31d)

**Comment by veger** [comment]
It is probably imprecision/rounding errors. (having 9.15 buildings to produce 1/s is most likely not exact 1/s)

In some places there is an 'epsilon' (a small enough/accepted discrepancy) introduced to allow for small (precision) differences. Either we need to be more precise (#80) or introduce epsilon in more places.

**Comment by have-fun-was-taken** [comment]
The error is not small.
1 Arqad Nest is produced, however 1 Arqad Nest is listed as Extra Product and 1 Arqad Nest is listed in Desired Products. In other words, the error is of the size of the whole production, which is 1/s. When checking with a debugger, its `linkFlow` is 1.

**Comment by have-fun-was-taken** [comment]
On second thought, I think it's better to first solve the [coloring](https://github.com/have-fun-was-taken/yafc-ce/pull/94), so it's easier to debug this one.

**Comment by veger** [comment]
Those 2 are the same: when there is over production the icon is (also) shown in the 'Extra products'. Now that I think about it: it is pretty confusing as there is not a full next extra produced...

Check this example:
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/171827/2f85abea-874f-4fd6-8f63-2a5f92972cbf)

A full assembler is able to produce 4 copper cable per second (this is correct/shown).
I requested 1 copper cable per second.
The extra production is thus 4 - 1 = 3 copper cable per second.

But extra products shows the full production instead as extra product.

**Comment by have-fun-was-taken** [comment]
Ah, so the result is not wrong, but the extra products of overconsumption do not account for the desired products. That needs to be explained somewhere or fixed somehow, but I don't know how yet.

**Comment by veger** [comment]
Indeed

Ideally it gets fixed, as there are no 4/s extra cables, only 3/s. So technically this is wrong. I just didn't notice (anymore), as I am used this this behavior.

**Comment by Dorus** [comment]
I'm trying a few things, and it seems to go wrong when we combine fixed building count with allow overproduction. Not only does it sometimes forget to subtract desired products from extra products, i've also found a setup where product flat out goes missing without reporting it in extra product:
![afbeelding](https://github.com/have-fun-was-taken/yafc-ce/assets/4461459/1cd6fad9-897f-40a3-9583-2d38e1084269)
7 vrauiks/sec are produced, 1 is consumer, 5 are desired, 1 goes ???

![afbeelding](https://github.com/have-fun-was-taken/yafc-ce/assets/4461459/01d1f16f-c677-40d3-9049-3667ce678d1b)

(speaking off, the link summary could use some work too, like reporting how much desired product or overproduction is detected)

**Comment by veger** [comment]
> 7 vrauiks/sec are produced, 1 is consumer, 5 are desired, 1 goes ???

hm... interesting... I once in a while see some weird summaries as well. I wrote it down to the summary being broken (I do not use it a lot for this reason), but in this case the actual solver messed up? It should always solve to  zero surplus (unless overproduction is allowed, which is not the case here), but even if there is a surplus it should show in 'Extra products'..!
